In [ ]:
import numpy as np
map = [
       [0,1,0,0,0],
       [0,0,1,0,0],
       [0,1,1,0,1],
       [0,1,0,0,1],
       [0,0,0,0,0],
]
map = np.array(map)
print("Time 0:")
print(map)

Time 0:
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 0 1]
 [0 1 0 0 1]
 [0 0 0 0 0]]


In [14]:
def count_live_neighbors(map, i, j):
    neighbor_count = 0
    for m in range(i-1, i+2):
      for n in range(j-1, j+2):
        if(m!=i and n!=j and n>1 and n<5 and m>-1 and m<5):
          if(map[m,n]==1):
            neighbor_count =+1

    return neighbor_count 

def flip(map, i, j):
    if (count_live_neighbors(map, i, j) == 2 and map[i,j] == 1):
      return False
    elif (count_live_neighbors(map, i, j) < 2 and map[i,j] == 1):
      return True
    elif (count_live_neighbors(map, i, j) > 2 and map[i,j] == 1):
      return True
    else:
      return False

In [15]:
# t = 1 to 20
for t in range(1,21):
    new_map = np.zeros(map.shape, dtype=int)
    for i in range(map.shape[0]):
        for j in range(map.shape[1]):
            flip_flag = flip(map, i, j)
            if flip_flag==True:
                new_map[i,j] = 1 - map[i,j]
            else:
                new_map[i,j] = map[i,j]

    map = new_map
    print("Time {}:".format(t))
    print(map)

Time 1:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 2:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 3:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 4:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 5:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 6:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 7:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 8:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 9:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 10:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 11:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 12:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 13:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time 14:
[[0 0 0 0 0]
 [0 0 0 0 0]